
  name: bd-sig-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.5.0
        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackduck_url: https://us03-sup-hub-williamson-test2.nprd.sig.synopsys.com/
          blackduck_apiToken: ZmMzMzhlMWItM2M3OS00OWQyLThmNzItMjdlNjYwYjI3NTk3OjI5OTZjMzI4LTZmZGMtNDEwMi04ODFiLTM1NmY1OWZiYjRkOQ==
          blackduck_scan_full: true
          ### Accepts Multiple Values
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
          # blackduck_fixpr_enabled: true
          # blackduck_fixpr_maxCount: 5
          # blackduck_fixpr_filter_severities: 'CRITICAL,HIGH'
          # blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
      
